### ISSUE TITLE
The Conv3D layer at the end of Seq2Seq class

### ISSUE THREAD

**Issue by smhassanerfani** [tsugumi-sys/SA-ConvLSTM-Pytorch#100]
Hi @tsugumi-sys,
Thank you for such a clean and professional implementation. I was wondering if you could explain a bit more about the 3D Convolutional layer you added at the end of your Seq2Seq classes. I read the original paper on [Self-Attention ConvLSTM for Spatiotemporal Prediction](https://ojs.aaai.org/index.php/AAAI/article/view/6819), but I didn't encounter such a layer there.

As far as I understand, Seq2Seq architectures generally consist of separate encoder and decoder parts for encoding the inputs and generating the sequence of target variables. Could you explain how you came to the decision to add the 3D convolutional layer and how your model benefits from it? I would also appreciate it if you could confirm whether this approach aligns with the original implementation.

**Comment by tsugumi-sys** [comment]
@smhassanerfani 
Hi, thank you for asking!
I used Conv3d for spatial and temporal convolution and it benefits for better predictions.

I remember that I referenced some papers (not that of SA ConvLSTM) and implementations on GitHub, but I forgot them because it was 3 or 4 years ago. Sorry ...

![image](https://github.com/user-attachments/assets/83a91495-d96d-4a34-a21e-619035ea8445)

**Comment by smhassanerfani** [comment]
Great! Thank you for your response and the wonderful illustration!
